spring.application.name=arsite

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nootnootadam@gmail.com
spring.mail.password=rmlu ewya drjp zvxn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true